Vagrant.configure("2") do |config|
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.network "private_network", ip: "192.168.10.150"
    db.hostsupdater.aliases = ["database.local"]
    #pass environment/db along, which contains the config files.
    db.vm.synced_folder "environment/db", "/home/environment"
    db.vm.provision "shell", path: "environment/db/provision_db.sh", privileged: false
  end

  config.vm.define "app" do |app|
    app.vm.box = "ubuntu/xenial64"
    app.vm.network "private_network", ip: "192.168.10.100"
    app.hostsupdater.aliases = ["development.local"]
    app.vm.synced_folder "app", "/home/app"
    app.vm.synced_folder "environment/app", "/home/environment"
    app.vm.provision "shell", path: "environment/app/provision_app.sh", privileged: false
    
  end

end